using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using UnityEngine;
using UnityEngine.XR.iOS;

/**
	TODO
 */
public class ARAddAnchorToPlane : MonoBehaviour {


	public GameObject prefabObject;
    public float maxRayDistance = 30.0f;
    public LayerMask collisionLayerMask;


    private void RaycastAddObject () {
        Ray ray = Camera.main.ScreenPointToRay (Input.mousePosition);
        RaycastHit hit;

        //we'll try to hit one of the plane collider gameobjects that were generated by the plugin
        //effectively similar to calling HitTest with ARHitTestResultType.ARHitTestResultTypeExistingPlaneUsingExtent
        if (Physics.Raycast (ray, out hit, maxRayDistance, collisionLayerMask)) {
            //we're going to get the position from the contact point
            GameObject clone = Instantiate(prefabObject, hit.point, hit.transform.rotation);
        }
    }

	// Update is called once per frame
    #if UNITY_EDITOR 
    void Update () {
        if (Input.GetMouseButtonDown (0)) {
            RaycastAddObject();
        }
    }
    #else
	void Update () {
		if (Input.touchCount > 0 && Input.GetTouch(0).phase == TouchPhase.Began)
		{
			RaycastAddObject();
		}
	}
    #endif
}
